version: "3"
services:
  postgres:
    image: "${IMAGE_NAME_POSTGRES_PROD}:latest"
    container_name: fibonacci-calc_postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: "${IMAGE_NAME_REDIS_PROD}"
    container_name: fibonacci-calc_redis_prod
  proxy:
    image: "${IMAGE_NAME_PROXY_PROD}"
    build:
      dockerfile: Dockerfile
      context: ./fibonacci-calc-proxy
    depends_on:
      - api
      - frontend
    container_name: fibonacci-calc_proxy_prod
    restart: always
    ports:
      - "3050:80"
  api:
    image: "${IMAGE_NAME_SERVER_PROD}"
    build:
      dockerfile: Dockerfile
      context: ./fibonacci-calc-server
    depends_on:
      - postgres
      - redis
    container_name: fibonacci-calc_api_prod
    # explore to name service "server" but be reachable via "api"
    # networks:
    #  default:
    #    aliases:
    #      - api
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
  frontend:
    image: ${IMAGE_NAME_FRONTEND_PROD}
    build:
      dockerfile: Dockerfile
      context: ./fibonacci-calc-frontend
    container_name: fibonacci-calc_frontend_prod
    depends_on:
      - api
  worker:
    image: ${IMAGE_NAME_WORKER_PROD}
    build:
      dockerfile: Dockerfile
      context: ./fibonacci-calc-worker
    container_name: fibonacci-calc_worker_prod
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
