version: "3"
services:
  postgres:
    image: "postgres:latest"
    ports:
      - "5433:5432"
  redis:
    image: "redis:latest"
  proxy:
    build:
      dockerfile: Dockerfile
      context: ./fibonacci-calc-proxy
    restart: always
    ports:
      - "3050:80"
    volumes:
      - ./fibonacci-calc-proxy/nginx.conf:/etc/nginx/conf.d/default.conf # do mount this over
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./fibonacci-calc-server
    # explore to name service "server" but be reachable via "api"
    # networks:
    #  default:
    #    aliases:
    #      - api
    volumes:
      - /usr/app/node_modules # do NOT mount this over
      - ./fibonacci-calc-server/package.json:/usr/app/package.json # do mount this over
      - ./fibonacci-calc-server/yarn.lock:/usr/app/yarn.lock # do mount this over
      - ./fibonacci-calc-server/src:/usr/app/src # do mount this over
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./fibonacci-calc-frontend
    volumes:
      - /usr/app/node_modules # do NOT mount this over
      - ./fibonacci-calc-frontend/package.json:/usr/app/package.json # do mount this over
      - ./fibonacci-calc-frontend/yarn.lock:/usr/app/yarn.lock # do mount this over
      - ./fibonacci-calc-frontend/src:/usr/app/src # do mount this over
      - ./fibonacci-calc-frontend/public:/usr/app/public # do mount this over
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./fibonacci-calc-worker
    volumes:
      - /usr/app/node_modules # do NOT mount this over
      - ./fibonacci-calc-worker/package.json:/usr/app/package.json # do mount this over
      - ./fibonacci-calc-worker/yarn.lock:/usr/app/yarn.lock # do mount this over
      - ./fibonacci-calc-worker/src:/usr/app/src # do mount this over
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
